name: build-and-deploy
on:
  push:
    branches:
      - hydra-parachain
  workflow_dispatch:
  pull_request:

env:
  RELAY_CHAIN_VERSION: v0.9.28

jobs:
  version-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    outputs:
      runtime-upgraded: ${{ steps.check-runtime.outputs.upgraded }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Check runtime upgrade
        id: check-runtime
        run: echo "upgraded=true" >> $GITHUB_OUTPUT

  test-upgrade-runtime:
    needs: [version-check]
    runs-on: ubuntu-latest
    if: ${{ needs.version-check.outputs.runtime-upgraded == 'true' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}